export const AL_BAHA_DESTINATIONS = [
  {
    slug: "dhee-ayn-marble-village",
    nameEn: "Dhee Ayn Marble Village",
    nameAr: "قرية ذي عين الرخامية",
    descEn:
      "A dramatic 400-year-old hilltop village built from white quartz stone, famous for layered architecture and mountain views.",
    descAr:
      "قرية تاريخية عمرها 400 عام بنيت من حجر الكوارتز الأبيض على قمة تل، تشتهر بعمارتها الطبقية وإطلالاتها الجبلية.",
    category: "ATTRACTION",
    lat: 19.9303,
    lng: 41.4436,
    avgDurationMins: 120,
    priceLevel: 1,
    rating: 4.6,
    reviewCount: 1840,
    tags: ["culture", "history", "architecture", "photo-spot", "unesco"],
    imageUrl: "https://images.unsplash.com/photo-1542401886-65d6c61db217?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1542401886-65d6c61db217?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1542401886-65d6c61db217?w=800"],
    openingHours: null,
    googlePlaceId: "ChIJV6FGr6AKPj4Rl_bVh8BZwCY",
    officialUrl: null,
    tripAdvisorUrl: "https://www.tripadvisor.com/Attraction_Review-g4405399-d8262853-Reviews-Thee_Ain_Village-Al_Baha_Al_Baha_Province.html",
    googleMapsUrl: "https://maps.google.com/?q=19.9303,41.4436",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "raghadan-forest-park",
    nameEn: "Raghadan Forest Park",
    nameAr: "منتزه رغدان الغابي",
    descEn:
      "Popular cloud-kissed highland forest with picnic terraces, viewpoints, and cool weather through most of the year.",
    descAr:
      "غابة مرتفعة محاطة بالغيوم مع مدرجات للتنزه ونقاط مشاهدة وطقس بارد معظم أيام السنة.",
    category: "NATURE",
    lat: 20.0311,
    lng: 41.4845,
    avgDurationMins: 150,
    priceLevel: 1,
    rating: 4.4,
    reviewCount: 1320,
    tags: ["nature", "family", "photo-spot", "cool-climate"],
    imageUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: "https://www.tripadvisor.com/Attraction_Review-g4405399-d4367773-Reviews-Raghadan_Park-Al_Baha_Al_Baha_Province.html",
    googleMapsUrl: "https://maps.google.com/?q=20.0311,41.4845",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-baha-cable-car",
    nameEn: "Al Baha Cable Car (Telefrik)",
    nameAr: "تلفريك الباحة",
    descEn:
      "Scenic cable car route linking highland points with sweeping views over valleys and terraced farms.",
    descAr:
      "خط تلفريك يربط بين المرتفعات مع إطلالات مذهلة على الوديان والمدرجات الزراعية.",
    category: "ADVENTURE",
    lat: 20.0001,
    lng: 41.4556,
    avgDurationMins: 90,
    priceLevel: 2,
    rating: 4.2,
    reviewCount: 740,
    tags: ["adventure", "views", "family", "mountains"],
    imageUrl: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1551632811-561732d1e306?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=20.0001,41.4556",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-baha-old-market",
    nameEn: "Al Baha Old Market (Souq Al Khamis)",
    nameAr: "سوق الخميس بالباحة",
    descEn:
      "Traditional market with local honey, handicrafts, mountain herbs, and regional dishes.",
    descAr:
      "سوق تقليدي يضم العسل المحلي والمنتجات الحرفية والأعشاب الجبلية والأطباق الإقليمية.",
    category: "SHOPPING",
    lat: 20.0069,
    lng: 41.4677,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.1,
    reviewCount: 510,
    tags: ["shopping", "culture", "food", "local"],
    imageUrl: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=20.0069,41.4677",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "shada-mountain-hike",
    nameEn: "Shada Mountain Trail",
    nameAr: "مسار جبل شدا الأعلى",
    descEn:
      "Granite mountain trail with rare flora, carved villages, and dramatic viewpoints at 2,200m elevation.",
    descAr:
      "مسار جبلي جرانيتي مع نباتات نادرة وقرى منحوتة ومناظر خلابة على ارتفاع 2,200 متر.",
    category: "NATURE",
    lat: 19.865,
    lng: 41.2942,
    avgDurationMins: 210,
    priceLevel: 1,
    rating: 4.7,
    reviewCount: 390,
    tags: ["nature", "hiking", "adventure", "photo-spot"],
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=19.865,41.2942",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-baha-botanical-garden",
    nameEn: "Al Baha Botanical Garden",
    nameAr: "الحديقة النباتية بالباحة",
    descEn:
      "Hillside botanical garden showcasing rare highland flora, medicinal plants, and terraced landscapes unique to the Hejaz region.",
    descAr:
      "حديقة نباتية على سفح الجبل تعرض نباتات المرتفعات النادرة والنباتات الطبية والمناظر المدرجة المميزة لمنطقة الحجاز.",
    category: "NATURE",
    lat: 20.0156,
    lng: 41.4712,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.3,
    reviewCount: 420,
    tags: ["nature", "garden", "family", "photography"],
    imageUrl: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=20.0156,41.4712",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-makhwah-terraces",
    nameEn: "Al Makhwah Agricultural Terraces",
    nameAr: "مدرجات المخواة الزراعية",
    descEn:
      "Ancient stone agricultural terraces carved into mountainsides, still used for growing banana, mango, and grains with traditional irrigation channels.",
    descAr:
      "مدرجات زراعية حجرية قديمة منحوتة في سفوح الجبال، لا تزال تُستخدم لزراعة الموز والمانجو والحبوب بقنوات ري تقليدية.",
    category: "ATTRACTION",
    lat: 19.7764,
    lng: 41.4332,
    avgDurationMins: 120,
    priceLevel: 1,
    rating: 4.4,
    reviewCount: 280,
    tags: ["agriculture", "history", "nature", "photography"],
    imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=19.7764,41.4332",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-baha-honey-experience",
    nameEn: "Al Baha Honey Farm Experience",
    nameAr: "تجربة مناحل عسل الباحة",
    descEn:
      "Visit traditional beekeeping farms in the highlands. Al Baha produces the finest Sidr honey in Saudi Arabia — taste, learn, and buy directly from beekeepers.",
    descAr:
      "زر مناحل تربية النحل التقليدية في المرتفعات. تنتج الباحة أجود عسل السدر في المملكة — تذوق وتعلم واشترِ مباشرة من النحالين.",
    category: "ATTRACTION",
    lat: 19.9842,
    lng: 41.4288,
    avgDurationMins: 90,
    priceLevel: 2,
    rating: 4.6,
    reviewCount: 530,
    tags: ["food", "culture", "nature", "local", "experience"],
    imageUrl: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=19.9842,41.4288",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "baljurashi-park",
    nameEn: "Baljurashi Park",
    nameAr: "منتزه بلجرشي",
    descEn:
      "A sprawling highland park with rose gardens, walking trails, and panoramic viewpoints overlooking the Tihama lowlands.",
    descAr:
      "منتزه مترامي الأطراف على المرتفعات مع حدائق ورد ومسارات مشي وإطلالات بانورامية على سهل تهامة.",
    category: "NATURE",
    lat: 19.8547,
    lng: 41.6032,
    avgDurationMins: 120,
    priceLevel: 1,
    rating: 4.3,
    reviewCount: 680,
    tags: ["nature", "family", "views", "gardens"],
    imageUrl: "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=19.8547,41.6032",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "fog-mountain-viewpoint",
    nameEn: "Fog Mountain Viewpoint (Jabal Al Dabaab)",
    nameAr: "جبل الضباب",
    descEn:
      "A dramatic mountain viewpoint above the cloud line, offering surreal views of fog rolling through valleys below.",
    descAr:
      "نقطة مشاهدة جبلية فوق خط الغيوم، توفر مناظر سريالية للضباب المتدحرج عبر الوديان.",
    category: "NATURE",
    lat: 19.9022,
    lng: 41.4018,
    avgDurationMins: 60,
    priceLevel: 1,
    rating: 4.8,
    reviewCount: 350,
    tags: ["nature", "photo-spot", "scenic", "mountains", "fog"],
    imageUrl: "https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=19.9022,41.4018",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-baha-heritage-museum",
    nameEn: "Al Baha Heritage Museum",
    nameAr: "متحف الباحة للتراث",
    descEn:
      "Regional museum documenting Al Baha's tribal history, traditional clothing, farming tools, and architectural models of historic hilltop villages.",
    descAr:
      "متحف إقليمي يوثق تاريخ الباحة القبلي والملابس التقليدية وأدوات الزراعة ونماذج معمارية للقرى التاريخية.",
    category: "ATTRACTION",
    lat: 20.0112,
    lng: 41.4689,
    avgDurationMins: 60,
    priceLevel: 1,
    rating: 4.0,
    reviewCount: 190,
    tags: ["museum", "culture", "history", "heritage"],
    imageUrl: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=20.0112,41.4689",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "wadi-al-janabeen",
    nameEn: "Wadi Al Janabeen",
    nameAr: "وادي الجنابين",
    descEn:
      "A lush green valley between dramatic cliff faces with natural springs, wild fig trees, and traditional stone houses.",
    descAr:
      "وادٍ أخضر خصب بين جروف صخرية مع ينابيع طبيعية وأشجار تين برية ومنازل حجرية تقليدية.",
    category: "NATURE",
    lat: 19.9518,
    lng: 41.3654,
    avgDurationMins: 150,
    priceLevel: 1,
    rating: 4.5,
    reviewCount: 240,
    tags: ["nature", "hiking", "valley", "springs", "photography"],
    imageUrl: "https://images.unsplash.com/photo-1472396961693-142e6e269027?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1472396961693-142e6e269027?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1472396961693-142e6e269027?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=19.9518,41.3654",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "makhwah-banana-farms",
    nameEn: "Makhwah Tropical Fruit Farms",
    nameAr: "مزارع الفواكه الاستوائية بالمخواة",
    descEn:
      "Visit tropical fruit orchards in the Tihama lowlands growing banana, papaya, and mango — a surprising contrast to the mountainous highlands.",
    descAr:
      "زر بساتين الفواكه الاستوائية في سهل تهامة حيث ينمو الموز والبابايا والمانجو — تناقض مدهش مع المرتفعات الجبلية.",
    category: "ATTRACTION",
    lat: 19.7832,
    lng: 41.4115,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 210,
    tags: ["food", "nature", "agriculture", "family", "local"],
    imageUrl: "https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=19.7832,41.4115",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-baha-cloud-forest-drive",
    nameEn: "Al Baha Cloud Forest Scenic Drive",
    nameAr: "طريق غابة الغيوم ذات المناظر الخلابة",
    descEn:
      "A winding mountain road through juniper forests often shrouded in mist, connecting the highlands to the Tihama coastal plain with spectacular hairpin turns.",
    descAr:
      "طريق جبلي متعرج عبر غابات العرعر المحاطة بالضباب، يربط المرتفعات بسهل تهامة الساحلي مع منعطفات مذهلة.",
    category: "ADVENTURE",
    lat: 19.9284,
    lng: 41.3856,
    avgDurationMins: 120,
    priceLevel: 1,
    rating: 4.6,
    reviewCount: 490,
    tags: ["scenic-drive", "nature", "adventure", "photography", "mountains"],
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=19.9284,41.3856",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-mukhwah-fortress",
    nameEn: "Al Mukhwah Historical Fortress",
    nameAr: "قلعة المخواة التاريخية",
    descEn:
      "Ottoman-era stone fortress overlooking the Tihama valley with thick walls and watch towers — a testament to the region's strategic importance.",
    descAr:
      "قلعة حجرية من العصر العثماني تطل على وادي تهامة بجدران سميكة وأبراج مراقبة — شاهد على الأهمية الاستراتيجية للمنطقة.",
    category: "ATTRACTION",
    lat: 19.7802,
    lng: 41.4388,
    avgDurationMins: 60,
    priceLevel: 1,
    rating: 4.1,
    reviewCount: 160,
    tags: ["history", "architecture", "culture", "fortress"],
    imageUrl: "https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=19.7802,41.4388",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-baha-national-park",
    nameEn: "Al-Baha National Park",
    nameAr: "منتزه الباحة الوطني",
    descEn:
      "Sprawling highland park with juniper forests, fog-draped valleys, and scenic lookout points. Features barbecue areas, walking trails, and a children's playground amid cool mountain air.",
    descAr:
      "منتزه مرتفعات واسع بغابات العرعر ووديان مغلفة بالضباب ونقاط إطلالة خلابة. يضم مناطق شواء ومسارات مشي وملعب أطفال في هواء الجبل العليل.",
    category: "NATURE",
    lat: 20.0000,
    lng: 41.4700,
    avgDurationMins: 180,
    priceLevel: 1,
    rating: 4.4,
    reviewCount: 3800,
    tags: ["park", "nature", "hiking", "fog", "family"],
    imageUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1920",
    imageUrls: [
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
    ],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=20.0000,41.4700",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "raghadan-castle",
    nameEn: "Raghadan Castle",
    nameAr: "قلعة رغدان",
    descEn:
      "Historic hilltop castle overlooking the Al-Baha valley, originally built as a defensive fortress. Offers panoramic views and insight into the region's tribal history.",
    descAr:
      "قلعة تاريخية على قمة تل تطل على وادي الباحة، بُنيت أصلاً كحصن دفاعي. توفر مناظر بانورامية ونظرة على تاريخ القبائل في المنطقة.",
    category: "CULTURAL",
    lat: 20.0100,
    lng: 41.4650,
    avgDurationMins: 60,
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 1600,
    tags: ["castle", "history", "views", "fortress", "heritage"],
    imageUrl: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=1920",
    imageUrls: [
      "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=800",
    ],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=20.0100,41.4650",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "shada-mountain",
    nameEn: "Shada Mountain Nature Reserve",
    nameAr: "محمية جبل شدا الطبيعية",
    descEn:
      "Biodiverse mountain reserve with rare Arabian wildlife including leopards and ibex. Features ancient terraced agriculture and endemic plants found nowhere else on Earth.",
    descAr:
      "محمية جبلية متنوعة بيولوجياً بحياة برية عربية نادرة تشمل الفهد والوعل. تضم زراعة مدرجات قديمة ونباتات مستوطنة لا توجد في أي مكان آخر.",
    category: "NATURE",
    lat: 19.8500,
    lng: 41.3000,
    avgDurationMins: 240,
    priceLevel: 1,
    rating: 4.6,
    reviewCount: 1200,
    tags: ["nature", "wildlife", "hiking", "biodiversity", "leopard"],
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1920",
    imageUrls: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    ],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=19.8500,41.3000",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "thee-ain-banana-farms",
    nameEn: "Thee Ain Banana Plantations",
    nameAr: "مزارع الموز في ذي عين",
    descEn:
      "Lush banana and tropical fruit plantations in the valley below the historic Thee Ain village. Tour the terraced farms, taste fresh tropical fruits, and enjoy the green microclimate.",
    descAr:
      "مزارع موز وفواكه استوائية خصبة في الوادي أسفل قرية ذي عين التاريخية. جولة في المزارع المدرجة وتذوق الفواكه الطازجة.",
    category: "NATURE",
    lat: 19.9300,
    lng: 41.4400,
    avgDurationMins: 120,
    priceLevel: 1,
    rating: 4.3,
    reviewCount: 2100,
    tags: ["farm", "tropical", "banana", "nature", "food"],
    imageUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1920",
    imageUrls: [
      "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800",
    ],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=19.9300,41.4400",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "bani-sariyah-village",
    nameEn: "Bani Sariyah Heritage Village",
    nameAr: "قرية بني سارية التراثية",
    descEn:
      "Beautifully preserved stone village perched on a cliff edge with traditional Baha architecture. Features narrow alleyways, watchtowers, and stunning valley views.",
    descAr:
      "قرية حجرية محفوظة بشكل جميل على حافة جرف بعمارة باحية تقليدية. تضم أزقة ضيقة وأبراج مراقبة وإطلالات خلابة على الوادي.",
    category: "CULTURAL",
    lat: 19.8600,
    lng: 41.3500,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.5,
    reviewCount: 1400,
    tags: ["village", "heritage", "stone", "architecture", "views"],
    imageUrl: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=1920",
    imageUrls: [
      "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=800",
    ],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=19.8600,41.3500",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
];

