export const AL_JAWF_DESTINATIONS = [
  {
    slug: "marid-castle",
    nameEn: "Marid Castle",
    nameAr: "قلعة مارد",
    descEn:
      "Ancient fortress in Dumat Al Jandal with commanding views and links to pre-Islamic Arab history dating back to the 1st century BC.",
    descAr:
      "قلعة قديمة في دومة الجندل تتميز بإطلالات مهيبة وروابط بالتاريخ العربي قبل الإسلام يعود تاريخها إلى القرن الأول قبل الميلاد.",
    category: "ATTRACTION",
    lat: 29.8097,
    lng: 39.8667,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.5,
    reviewCount: 960,
    tags: ["history", "culture", "architecture", "photo-spot", "ancient"],
    imageUrl: "https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: "https://www.tripadvisor.com/Attraction_Review-g1573775-d3910277-Reviews-Marid_Castle-Dumat_Al_Jandal_Al_Jawf_Province.html",
    googleMapsUrl: "https://maps.google.com/?q=29.8097,39.8667",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "rajajil-standing-stones",
    nameEn: "Rajajil Standing Stones",
    nameAr: "أعمدة الرجاجيل",
    descEn:
      "Mysterious megalithic stone columns dating back over 6,000 years, often called 'Saudi Arabia's Stonehenge' — one of the region's most important archaeological sites.",
    descAr:
      "أعمدة حجرية غامضة يتجاوز عمرها 6000 عام، تُسمى 'ستونهنج السعودية' — أحد أهم المواقع الأثرية في المنطقة.",
    category: "ATTRACTION",
    lat: 29.7693,
    lng: 40.1027,
    avgDurationMins: 100,
    priceLevel: 1,
    rating: 4.4,
    reviewCount: 540,
    tags: ["history", "archaeology", "ancient", "culture", "megalithic"],
    imageUrl: "https://images.unsplash.com/photo-1547234935-80c7145ec969?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1547234935-80c7145ec969?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1547234935-80c7145ec969?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: "https://www.tripadvisor.com/Attraction_Review-g1573775-d3910278-Reviews-Rajajil_Columns-Dumat_Al_Jandal_Al_Jawf_Province.html",
    googleMapsUrl: "https://maps.google.com/?q=29.7693,40.1027",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "dumat-lake-park",
    nameEn: "Dumat Al Jandal Lake",
    nameAr: "بحيرة دومة الجندل",
    descEn:
      "Beautiful freshwater lake surrounded by parks and boardwalks with stunning sunset views and seasonal migratory birds.",
    descAr:
      "بحيرة مياه عذبة جميلة محاطة بالحدائق والممرات الخشبية مع إطلالات غروب مذهلة وطيور مهاجرة موسمية.",
    category: "NATURE",
    lat: 29.8031,
    lng: 39.9012,
    avgDurationMins: 120,
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 460,
    tags: ["nature", "family", "sunset", "birds", "lake"],
    imageUrl: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=29.8031,39.9012",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-jawf-olive-farms",
    nameEn: "Al Jawf Olive Farms & Museum",
    nameAr: "مزارع ومتحف زيتون الجوف",
    descEn:
      "Al Jawf holds the Guinness record for the world's largest number of olive trees. Tour orchards, taste award-winning olive oil, and visit the Olive Museum.",
    descAr:
      "تحمل الجوف الرقم القياسي في غينيس لأكبر عدد أشجار زيتون في العالم. جولة في البساتين وتذوق زيت الزيتون الحائز على جوائز وزيارة متحف الزيتون.",
    category: "ATTRACTION",
    lat: 29.9904,
    lng: 40.2054,
    avgDurationMins: 110,
    priceLevel: 2,
    rating: 4.3,
    reviewCount: 330,
    tags: ["food", "culture", "nature", "local", "olive-oil"],
    imageUrl: "https://images.unsplash.com/photo-1505245208761-ba872912fac0?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1505245208761-ba872912fac0?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1505245208761-ba872912fac0?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=29.9904,40.2054",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "dumat-old-market",
    nameEn: "Dumat Al Jandal Old Market",
    nameAr: "سوق دومة الجندل القديم",
    descEn:
      "Traditional souq with local crafts, spices, and regional produce near the historic core of one of Arabia's oldest cities.",
    descAr:
      "سوق تقليدي يضم الحرف المحلية والتوابل والمنتجات الإقليمية بالقرب من المركز التاريخي لواحدة من أقدم مدن الجزيرة العربية.",
    category: "SHOPPING",
    lat: 29.8105,
    lng: 39.8687,
    avgDurationMins: 80,
    priceLevel: 1,
    rating: 4.1,
    reviewCount: 295,
    tags: ["shopping", "culture", "food", "heritage"],
    imageUrl: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=29.8105,39.8687",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "omar-ibn-al-khattab-mosque",
    nameEn: "Omar Ibn Al Khattab Mosque",
    nameAr: "مسجد عمر بن الخطاب",
    descEn:
      "One of the oldest mosques in Saudi Arabia, believed to date to the 7th century. Its stone minaret is considered one of the earliest in Islamic architecture.",
    descAr:
      "أحد أقدم المساجد في المملكة العربية السعودية، يُعتقد أنه يعود للقرن السابع الميلادي. تُعد مئذنته الحجرية من أقدم المآذن في العمارة الإسلامية.",
    category: "ATTRACTION",
    lat: 29.8108,
    lng: 39.8652,
    avgDurationMins: 45,
    priceLevel: 1,
    rating: 4.6,
    reviewCount: 680,
    tags: ["religion", "history", "architecture", "culture", "mosque"],
    imageUrl: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=29.8108,39.8652",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-jawf-desert-stargazing",
    nameEn: "Al Jawf Desert Stargazing",
    nameAr: "مراقبة النجوم في صحراء الجوف",
    descEn:
      "Al Jawf's remote desert offers some of the darkest skies in the Middle East — perfect for astrophotography and guided stargazing tours under the Milky Way.",
    descAr:
      "توفر صحراء الجوف النائية بعضًا من أحلك السماوات في الشرق الأوسط — مثالية للتصوير الفلكي وجولات مراقبة النجوم تحت درب التبانة.",
    category: "ADVENTURE",
    lat: 29.6543,
    lng: 40.0876,
    avgDurationMins: 180,
    priceLevel: 2,
    rating: 4.7,
    reviewCount: 180,
    tags: ["adventure", "stargazing", "desert", "photography", "night"],
    imageUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=29.6543,40.0876",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-jawf-naf-tunnel",
    nameEn: "Naf Tunnel (Ancient Water Channel)",
    nameAr: "نفق ناف (قناة المياه القديمة)",
    descEn:
      "Ancient underground water channel carved through rock in Dumat Al Jandal, showcasing remarkable Nabataean-era hydraulic engineering.",
    descAr:
      "قناة مياه قديمة تحت الأرض محفورة في الصخر في دومة الجندل، تعرض هندسة هيدروليكية نبطية رائعة.",
    category: "ATTRACTION",
    lat: 29.8112,
    lng: 39.8698,
    avgDurationMins: 60,
    priceLevel: 1,
    rating: 4.3,
    reviewCount: 210,
    tags: ["history", "archaeology", "engineering", "underground"],
    imageUrl: "https://images.unsplash.com/photo-1547234935-80c7145ec969?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1547234935-80c7145ec969?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1547234935-80c7145ec969?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=29.8112,39.8698",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "sakaka-city-promenade",
    nameEn: "Sakaka City Promenade & Park",
    nameAr: "كورنيش ومتنزه سكاكا",
    descEn:
      "Modern urban park in the capital city with fountains, play areas, walking paths, and evening entertainment along the main boulevard.",
    descAr:
      "حديقة حضرية حديثة في العاصمة مع نوافير ومناطق ألعاب ومسارات مشي وترفيه مسائي على طول الشارع الرئيسي.",
    category: "NATURE",
    lat: 29.9726,
    lng: 40.1981,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.0,
    reviewCount: 380,
    tags: ["city", "family", "park", "evening"],
    imageUrl: "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=29.9726,40.1981",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "qasr-za-abal",
    nameEn: "Qasr Za'abal (Za'abal Castle)",
    nameAr: "قصر زعبل",
    descEn:
      "A dramatic hilltop castle perched on a rocky outcrop in Sakaka with panoramic views of the city and surrounding desert.",
    descAr:
      "قلعة مهيبة على قمة تل صخري في سكاكا مع إطلالات بانورامية على المدينة والصحراء المحيطة.",
    category: "ATTRACTION",
    lat: 29.9788,
    lng: 40.2035,
    avgDurationMins: 60,
    priceLevel: 1,
    rating: 4.4,
    reviewCount: 520,
    tags: ["history", "castle", "views", "photography"],
    imageUrl: "https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=29.9788,40.2035",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-jawf-olive-festival",
    nameEn: "Al Jawf Olive Festival",
    nameAr: "مهرجان زيتون الجوف",
    descEn: "Annual celebration of Al Jawf's renowned olive harvest — the largest olive-producing region in Saudi Arabia. Features olive oil tasting, farm tours, and cultural shows.",
    descAr: "احتفال سنوي بموسم حصاد الزيتون في الجوف — أكبر منطقة إنتاج زيتون في السعودية. يضم تذوق زيت الزيتون وجولات مزارع وعروض ثقافية.",
    category: "EVENT",
    lat: 29.8100,
    lng: 39.8700,
    avgDurationMins: 180,
    priceLevel: 1,
    rating: 4.4,
    reviewCount: 320,
    tags: ["events", "food", "olive", "festival", "culture"],
    imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=29.8100,39.8700",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "rajajil-standing-stones",
    nameEn: "Al Rajajil Standing Stones",
    nameAr: "أعمدة الرجاجيل",
    descEn: "Mysterious 6,000-year-old standing stone columns arranged in groups, often called Saudi Arabia's Stonehenge. Among the most enigmatic archaeological sites in the Arabian Peninsula.",
    descAr: "أعمدة حجرية غامضة عمرها 6000 عام مرتبة في مجموعات، تُلقب بستونهنج السعودية. من أكثر المواقع الأثرية غموضًا في الجزيرة العربية.",
    category: "ATTRACTION",
    lat: 29.7916,
    lng: 39.7600,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.3,
    reviewCount: 180,
    tags: ["archaeology", "ancient", "history", "mystery", "photo-spot"],
    imageUrl: "https://images.unsplash.com/photo-1547234935-80c7145ec969?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1547234935-80c7145ec969?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1547234935-80c7145ec969?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=29.7916,39.7600",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "sakaka-traditional-souk",
    nameEn: "Sakaka Traditional Souk",
    nameAr: "سوق سكاكا التقليدي",
    descEn: "Bustling traditional market in the heart of Sakaka selling olive oil, dates, handicrafts, Bedouin jewelry, and local spices.",
    descAr: "سوق تقليدي نابض بالحياة في قلب سكاكا يبيع زيت الزيتون والتمور والحرف اليدوية والمجوهرات البدوية والتوابل المحلية.",
    category: "SHOPPING",
    lat: 29.9700,
    lng: 40.2100,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.1,
    reviewCount: 280,
    tags: ["shopping", "culture", "food", "souk", "olive-oil"],
    imageUrl: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=29.9700,40.2100",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "dumat-al-jandal-old-quarter",
    nameEn: "Dumat Al Jandal Old Quarter",
    nameAr: "حي دومة الجندل القديم",
    descEn: "Wander through the ancient stone-built streets of one of the oldest continuously inhabited towns in northern Arabia, with a labyrinth of alleyways, stone houses, and the iconic Omar Mosque.",
    descAr: "تجول في الشوارع الحجرية القديمة لواحدة من أقدم المدن المأهولة باستمرار في شمال الجزيرة العربية مع متاهة أزقة وبيوت حجرية ومسجد عمر الأيقوني.",
    category: "ATTRACTION",
    lat: 29.8150,
    lng: 39.8650,
    avgDurationMins: 120,
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 350,
    tags: ["history", "heritage", "architecture", "walking", "ancient"],
    imageUrl: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=29.8150,39.8650",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-jawf-olive-farm-tour",
    nameEn: "Al Jawf Olive Farm Tour",
    nameAr: "جولة مزارع زيتون الجوف",
    descEn: "Tour the vast olive groves of Al Jawf — home to over 20 million olive trees. Learn the pressing process, taste premium extra-virgin olive oil, and buy directly from the source.",
    descAr: "جولة في بساتين الزيتون الشاسعة في الجوف — موطن أكثر من 20 مليون شجرة زيتون. تعلم عملية العصر وتذوق زيت الزيتون البكر الفاخر واشترِ مباشرة من المصدر.",
    category: "NATURE",
    lat: 29.8500,
    lng: 39.9200,
    avgDurationMins: 150,
    priceLevel: 1,
    rating: 4.5,
    reviewCount: 210,
    tags: ["nature", "food", "farm", "olive", "culture"],
    imageUrl: "https://images.unsplash.com/photo-1472396961693-142e6e269027?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1472396961693-142e6e269027?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1472396961693-142e6e269027?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=29.8500,39.9200",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "qasr-kaf-castle",
    nameEn: "Qasr Kaf Ancient Castle",
    nameAr: "قصر كاف القديم",
    descEn:
      "Well-preserved ancient castle in the village of Kaf, featuring multi-story mud-brick towers, traditional courtyards, and a museum documenting northern Saudi heritage.",
    descAr:
      "قلعة قديمة محفوظة جيداً في قرية كاف، تضم أبراج طينية متعددة الطوابق وأفنية تقليدية ومتحف يوثق تراث شمال السعودية.",
    category: "CULTURAL",
    lat: 31.3600,
    lng: 37.1400,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.3,
    reviewCount: 1100,
    tags: ["castle", "heritage", "museum", "mud-brick", "history"],
    imageUrl: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=1920",
    imageUrls: [
      "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=800",
    ],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=31.3600,37.1400",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-jawf-olive-press",
    nameEn: "Al-Jawf Olive Press Museum",
    nameAr: "متحف معصرة الزيتون بالجوف",
    descEn:
      "Museum dedicated to Al-Jawf's thriving olive oil industry, the largest in Saudi Arabia. See traditional stone presses, learn about modern production, and sample award-winning oils.",
    descAr:
      "متحف مخصص لصناعة زيت الزيتون المزدهرة في الجوف، الأكبر في السعودية. شاهد المعاصر الحجرية التقليدية وتعرف على الإنتاج الحديث وتذوق زيوتاً حائزة على جوائز.",
    category: "CULTURAL",
    lat: 29.8700,
    lng: 39.8700,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 900,
    tags: ["museum", "olive-oil", "food", "culture", "agriculture"],
    imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=1920",
    imageUrls: [
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800",
    ],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=29.8700,39.8700",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-jawf-desert-race",
    nameEn: "Al-Jawf Desert Camel Racing",
    nameAr: "سباق الإبل بصحراء الجوف",
    descEn:
      "Thrilling traditional camel races held on desert tracks during winter. Watch Bedouin jockeys race their prized camels while enjoying Arabic coffee and festival atmosphere.",
    descAr:
      "سباقات إبل تقليدية مثيرة تُقام على مضامير صحراوية خلال الشتاء. شاهد فرسان بدو يتسابقون بإبلهم الثمينة مع الاستمتاع بالقهوة العربية.",
    category: "ENTERTAINMENT",
    lat: 29.7500,
    lng: 40.0000,
    avgDurationMins: 180,
    priceLevel: 1,
    rating: 4.4,
    reviewCount: 1300,
    tags: ["camel", "racing", "bedouin", "desert", "tradition"],
    imageUrl: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=1920",
    imageUrls: [
      "https://images.unsplash.com/photo-1549490349-8643362247b5?w=800",
    ],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=29.7500,40.0000",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "nabbah-spring",
    nameEn: "Nabbah Natural Spring",
    nameAr: "نبع نباه الطبيعي",
    descEn:
      "Natural freshwater spring in the Al-Jawf desert, creating a lush oasis with palm trees and green vegetation in the otherwise arid landscape. A peaceful spot for picnics.",
    descAr:
      "نبع ماء عذب طبيعي في صحراء الجوف يشكل واحة خضراء خصبة بأشجار النخيل والنباتات وسط المناظر القاحلة. مكان هادئ للنزه.",
    category: "NATURE",
    lat: 29.9500,
    lng: 39.7500,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.0,
    reviewCount: 600,
    tags: ["spring", "oasis", "nature", "desert", "picnic"],
    imageUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1920",
    imageUrls: [
      "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800",
    ],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=29.9500,39.7500",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "qasr-al-basha",
    nameEn: "Qasr Al-Basha (Pasha's Palace)",
    nameAr: "قصر الباشا",
    descEn:
      "Ottoman-era governor's palace in Sakaka, now a regional museum exhibiting traditional costumes, weapons, manuscripts, and agricultural tools from the Al-Jawf region.",
    descAr:
      "قصر الوالي العثماني في سكاكا، الآن متحف إقليمي يعرض أزياء تقليدية وأسلحة ومخطوطات وأدوات زراعية من منطقة الجوف.",
    category: "CULTURAL",
    lat: 29.9700,
    lng: 40.2000,
    avgDurationMins: 60,
    priceLevel: 1,
    rating: 4.1,
    reviewCount: 800,
    tags: ["palace", "museum", "ottoman", "history", "heritage"],
    imageUrl: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=1920",
    imageUrls: [
      "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=800",
    ],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=29.9700,40.2000",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
];

