export const AL_QASSIM_DESTINATIONS = [
  {
    slug: "buraidah-date-market",
    nameEn: "Buraidah Date Market",
    nameAr: "سوق تمور بريدة",
    descEn:
      "One of the world's largest date markets with seasonal auctions, dozens of premium date varieties, and a vibrant atmosphere during harvest season (Aug-Oct).",
    descAr:
      "واحد من أكبر أسواق التمور في العالم مع مزادات موسمية وعشرات أصناف التمور الفاخرة وأجواء حيوية خلال موسم الحصاد (أغسطس-أكتوبر).",
    category: "SHOPPING",
    lat: 26.3552,
    lng: 43.9682,
    avgDurationMins: 120,
    priceLevel: 1,
    rating: 4.6,
    reviewCount: 1880,
    tags: ["shopping", "food", "culture", "local", "dates"],
    imageUrl: "https://images.unsplash.com/photo-1597690070758-f1dfb5506e07?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1597690070758-f1dfb5506e07?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1597690070758-f1dfb5506e07?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: "https://www.tripadvisor.com/Attraction_Review-g2057893-d12277884-Reviews-Buraidah_Date_Market-Buraydah_Al_Qassim_Province.html",
    googleMapsUrl: "https://maps.google.com/?q=26.3552,43.9682",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "unaizah-heritage-village",
    nameEn: "Unaizah Heritage Village",
    nameAr: "قرية عنيزة التراثية",
    descEn:
      "Preserved Najdi-style district with handicrafts, local cuisine, and cultural showcases in one of the region's most historic cities.",
    descAr:
      "حي محفوظ بالطراز النجدي مع الحرف اليدوية والمأكولات المحلية والعروض الثقافية في واحدة من أعرق مدن المنطقة.",
    category: "ATTRACTION",
    lat: 26.0919,
    lng: 43.9939,
    avgDurationMins: 100,
    priceLevel: 1,
    rating: 4.3,
    reviewCount: 710,
    tags: ["culture", "history", "architecture", "food", "heritage"],
    imageUrl: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=26.0919,43.9939",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "king-khalid-park-buraidah",
    nameEn: "King Khalid Park, Buraidah",
    nameAr: "حديقة الملك خالد ببريدة",
    descEn:
      "Urban green park with walking tracks, kids zones, event stages, and seasonal festivals for families.",
    descAr:
      "حديقة حضرية خضراء مع مسارات للمشي ومناطق ألعاب الأطفال ومنصات فعاليات ومهرجانات موسمية للعائلات.",
    category: "NATURE",
    lat: 26.3596,
    lng: 43.9967,
    avgDurationMins: 110,
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 680,
    tags: ["nature", "family", "city", "events"],
    imageUrl: "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=26.3596,43.9967",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-musawkaf-market",
    nameEn: "Al Musawkaf Historic Market",
    nameAr: "سوق المسوكف التاريخي",
    descEn:
      "Restored traditional market in Unaizah known for antiques, sweets, local Kleicha cookies, and craft stores.",
    descAr:
      "سوق تقليدي مُرمّم في عنيزة يشتهر بالتحف والحلويات وبسكويت الكليجة المحلي ومحلات الحرف.",
    category: "SHOPPING",
    lat: 26.0865,
    lng: 43.9914,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.4,
    reviewCount: 550,
    tags: ["shopping", "culture", "history", "local", "sweets"],
    imageUrl: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=26.0865,43.9914",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "qassim-farm-experience",
    nameEn: "Qassim Farm Stay Experience",
    nameAr: "تجربة الإقامة في مزارع القصيم",
    descEn:
      "Hands-on farm stays and orchard tours featuring dates, citrus, pomegranate, and traditional Saudi hospitality.",
    descAr:
      "إقامات عملية في المزارع وجولات في البساتين تشمل التمور والحمضيات والرمان والضيافة السعودية التقليدية.",
    category: "ATTRACTION",
    lat: 26.2804,
    lng: 43.8429,
    avgDurationMins: 180,
    priceLevel: 2,
    rating: 4.5,
    reviewCount: 290,
    tags: ["nature", "food", "culture", "family", "farm"],
    imageUrl: "https://images.unsplash.com/photo-1472396961693-142e6e269027?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1472396961693-142e6e269027?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1472396961693-142e6e269027?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=26.2804,43.8429",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "qassim-camel-market",
    nameEn: "Qassim Camel Market",
    nameAr: "سوق الإبل بالقصيم",
    descEn:
      "One of the largest camel markets in the Middle East where hundreds of camels are traded daily. An authentic window into Bedouin trading culture.",
    descAr:
      "أحد أكبر أسواق الإبل في الشرق الأوسط حيث يُتاجر بمئات الإبل يوميًا. نافذة أصيلة على ثقافة التجارة البدوية.",
    category: "ATTRACTION",
    lat: 26.3218,
    lng: 43.9456,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.5,
    reviewCount: 620,
    tags: ["culture", "local", "animals", "authentic", "market"],
    imageUrl: "https://images.unsplash.com/photo-1549492423-400259a2e574?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1549492423-400259a2e574?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1549492423-400259a2e574?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=26.3218,43.9456",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "kleicha-tasting-unaizah",
    nameEn: "Kleicha Cookie Tasting Experience",
    nameAr: "تجربة تذوق الكليجة في عنيزة",
    descEn:
      "Unaizah is the capital of Kleicha — Saudi Arabia's beloved date-filled cookie. Visit bakeries, learn the recipe, and taste fresh batches.",
    descAr:
      "عنيزة هي عاصمة الكليجة — الكعكة المحشوة بالتمر المحبوبة في السعودية. زر المخابز وتعلم الوصفة وتذوق الدفعات الطازجة.",
    category: "RESTAURANT",
    lat: 26.0898,
    lng: 43.9872,
    avgDurationMins: 60,
    priceLevel: 1,
    rating: 4.6,
    reviewCount: 430,
    tags: ["food", "sweets", "culture", "local", "experience"],
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=26.0898,43.9872",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-bassam-heritage-house",
    nameEn: "Al Bassam Heritage House",
    nameAr: "بيت البسام التراثي",
    descEn:
      "Beautifully restored Najdi house in Unaizah with traditional courtyard architecture, showcasing the lifestyle of wealthy merchant families.",
    descAr:
      "بيت نجدي مُرمم بشكل جميل في عنيزة بعمارة الفناء التقليدية، يعرض نمط حياة عائلات التجار الأثرياء.",
    category: "ATTRACTION",
    lat: 26.0854,
    lng: 43.9928,
    avgDurationMins: 60,
    priceLevel: 1,
    rating: 4.3,
    reviewCount: 340,
    tags: ["history", "architecture", "culture", "heritage", "house"],
    imageUrl: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=26.0854,43.9928",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "qassim-spring-flower-festival",
    nameEn: "Qassim Spring Flower Festival",
    nameAr: "مهرجان ربيع القصيم للزهور",
    descEn:
      "Annual spring flower festival (Mar-Apr) featuring millions of blooms, garden exhibits, local food stalls, and family entertainment.",
    descAr:
      "مهرجان سنوي لزهور الربيع (مارس-أبريل) يضم ملايين الزهور ومعارض الحدائق وأكشاك الطعام المحلي والترفيه العائلي.",
    category: "EVENT",
    lat: 26.3264,
    lng: 43.9754,
    avgDurationMins: 180,
    priceLevel: 1,
    rating: 4.4,
    reviewCount: 720,
    tags: ["events", "flowers", "family", "seasonal", "festival"],
    imageUrl: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=26.3264,43.9754",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "qassim-pomegranate-orchards",
    nameEn: "Qassim Pomegranate Orchards",
    nameAr: "بساتين رمان القصيم",
    descEn:
      "Visit sprawling pomegranate orchards during harvest season (Sep-Nov). Taste fresh pomegranate juice and buy varieties you won't find anywhere else.",
    descAr:
      "زر بساتين الرمان الشاسعة خلال موسم الحصاد (سبتمبر-نوفمبر). تذوق عصير الرمان الطازج واشترِ أصنافًا لن تجدها في أي مكان آخر.",
    category: "NATURE",
    lat: 26.1542,
    lng: 43.8976,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.3,
    reviewCount: 260,
    tags: ["nature", "food", "agriculture", "seasonal", "farm"],
    imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=26.1542,43.8976",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "uyun-al-jiwa-parks",
    nameEn: "Uyun Al-Jiwa Valley Parks",
    nameAr: "منتزهات وادي عيون الجواء",
    descEn: "A string of scenic parks along Uyun Al-Jiwa valley with date palm groves, natural springs, walking paths, and family picnic areas.",
    descAr: "سلسلة من المنتزهات الخلابة على طول وادي عيون الجواء مع بساتين نخيل وينابيع طبيعية ومسارات مشي ومناطق نزهات عائلية.",
    category: "NATURE",
    lat: 26.0300,
    lng: 43.9500,
    avgDurationMins: 120,
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 450,
    tags: ["nature", "family", "park", "walking", "springs"],
    imageUrl: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=26.0300,43.9500",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "ar-rass-heritage-village",
    nameEn: "Ar Rass Heritage Village",
    nameAr: "قرية الرس التراثية",
    descEn: "Historic village in Ar Rass known for its famous battle against Ibrahim Pasha and preserved Ottoman-era fortifications and traditional architecture.",
    descAr: "قرية تاريخية في الرس تشتهر بمعركتها الشهيرة ضد إبراهيم باشا وتحصيناتها العثمانية المحفوظة وعمارتها التقليدية.",
    category: "ATTRACTION",
    lat: 25.8650,
    lng: 43.4950,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.0,
    reviewCount: 220,
    tags: ["history", "heritage", "architecture", "culture"],
    imageUrl: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=25.8650,43.4950",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "qassim-honey-market",
    nameEn: "Qassim Honey & Saffron Market",
    nameAr: "سوق العسل والزعفران بالقصيم",
    descEn: "Specialized market selling premium Saudi honey varieties (sidr, sumra, talh), saffron, herbal remedies, and dried herbs from local beekeepers and farmers.",
    descAr: "سوق متخصص يبيع أصناف العسل السعودي الفاخر (السدر والسمرة والطلح) والزعفران والعلاج بالأعشاب والأعشاب المجففة من النحالين والمزارعين المحليين.",
    category: "SHOPPING",
    lat: 26.3400,
    lng: 43.9600,
    avgDurationMins: 60,
    priceLevel: 2,
    rating: 4.4,
    reviewCount: 380,
    tags: ["shopping", "food", "honey", "local", "herbs"],
    imageUrl: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=26.3400,43.9600",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "badana-fort-qassim",
    nameEn: "Badana Fort",
    nameAr: "قصر بدنة",
    descEn: "Well-preserved historical fortress in Al Badayea featuring traditional Najdi mud-brick architecture, watchtowers, and a glimpse into the region's tribal past.",
    descAr: "قلعة تاريخية محفوظة جيدًا في البدائع بعمارة نجدية تقليدية من الطوب اللبن وأبراج مراقبة ولمحة عن ماضي المنطقة القبلي.",
    category: "ATTRACTION",
    lat: 26.1000,
    lng: 44.0200,
    avgDurationMins: 60,
    priceLevel: 1,
    rating: 3.9,
    reviewCount: 150,
    tags: ["history", "architecture", "fort", "heritage"],
    imageUrl: "https://images.unsplash.com/photo-1553522991-71439aa8c8e1?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1553522991-71439aa8c8e1?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1553522991-71439aa8c8e1?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=26.1000,44.0200",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "qassim-traditional-cuisine",
    nameEn: "Qassim Traditional Cuisine Experience",
    nameAr: "تجربة المطبخ القصيمي التقليدي",
    descEn: "Taste authentic Qassimi dishes — jareesh (cracked wheat), marqooq (thin bread stew), qursan, and Kabsa Qassimi — at a traditional family-style restaurant.",
    descAr: "تذوق أطباق قصيمية أصيلة — الجريش والمرقوق والقرصان وكبسة القصيمي — في مطعم على الطريقة العائلية التقليدية.",
    category: "RESTAURANT",
    lat: 26.3500,
    lng: 43.9750,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.5,
    reviewCount: 520,
    tags: ["food", "traditional", "culture", "local", "cuisine"],
    imageUrl: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=26.3500,43.9750",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
];

