export const NAJRAN_DESTINATIONS = [
  {
    slug: "al-ukhdood-archaeological-site",
    nameEn: "Al Ukhdood Archaeological Site",
    nameAr: "موقع الأخدود الأثري",
    descEn:
      "Major excavation zone linked to ancient South Arabian civilizations with inscriptions, ruins, and rock carvings dating back over 2,000 years.",
    descAr:
      "منطقة تنقيب رئيسية مرتبطة بالحضارات العربية الجنوبية القديمة مع نقوش وآثار ورسوم صخرية يتجاوز عمرها 2000 عام.",
    category: "ATTRACTION",
    lat: 17.484,
    lng: 44.0992,
    avgDurationMins: 120,
    priceLevel: 1,
    rating: 4.5,
    reviewCount: 840,
    tags: ["history", "archaeology", "culture", "photo-spot", "ancient"],
    imageUrl: "https://images.unsplash.com/photo-1547234935-80c7145ec969?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1547234935-80c7145ec969?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1547234935-80c7145ec969?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: "https://www.tripadvisor.com/Attraction_Review-g2711874-d12277839-Reviews-Al_Ukhdood-Najran_Najran_Province.html",
    googleMapsUrl: "https://maps.google.com/?q=17.484,44.0992",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "najran-fort-emara-palace",
    nameEn: "Emara Palace (Najran Fort)",
    nameAr: "قصر الإمارة التاريخي",
    descEn:
      "Historic mud-brick fort and former regional governor's palace in central Najran, a masterpiece of Najrani architectural style with five towers.",
    descAr:
      "قلعة من الطوب اللبن وقصر الحاكم الإقليمي السابق في وسط نجران، تحفة معمارية نجرانية بخمسة أبراج.",
    category: "ATTRACTION",
    lat: 17.4923,
    lng: 44.1311,
    avgDurationMins: 80,
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 470,
    tags: ["history", "culture", "architecture", "heritage"],
    imageUrl: "https://images.unsplash.com/photo-1542401886-65d6c61db217?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1542401886-65d6c61db217?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1542401886-65d6c61db217?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=17.4923,44.1311",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "aba-al-saud-market",
    nameEn: "Aba Al Saud Traditional Market",
    nameAr: "سوق أبا السعود التقليدي",
    descEn:
      "Known for silverwork, janbiya daggers, fabrics, and regional spices in a lively souq setting.",
    descAr:
      "يشتهر بالأعمال الفضية وخناجر الجنبية والأقمشة والتوابل الإقليمية في أجواء سوق تقليدي حيوي.",
    category: "SHOPPING",
    lat: 17.4964,
    lng: 44.1243,
    avgDurationMins: 100,
    priceLevel: 1,
    rating: 4.3,
    reviewCount: 420,
    tags: ["shopping", "culture", "local", "crafts"],
    imageUrl: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=17.4964,44.1243",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "najran-dam-park",
    nameEn: "Najran Dam & Lake Park",
    nameAr: "منتزه سد وبحيرة نجران",
    descEn:
      "Popular family outing area with lake views, shaded seating, evening walks, and a dramatic dam backdrop.",
    descAr:
      "منطقة عائلية شهيرة مع إطلالات على البحيرة ومقاعد مظللة ونزهات مسائية وخلفية سد مثيرة.",
    category: "NATURE",
    lat: 17.6145,
    lng: 44.3116,
    avgDurationMins: 120,
    priceLevel: 1,
    rating: 4.1,
    reviewCount: 360,
    tags: ["nature", "family", "sunset", "city"],
    imageUrl: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=17.6145,44.3116",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "hima-cultural-area",
    nameEn: "Hima Cultural Area",
    nameAr: "منطقة حمى الثقافية",
    descEn:
      "UNESCO World Heritage Site with expansive rock-art and inscription landscape spanning thousands of years of human history along ancient caravan routes.",
    descAr:
      "موقع تراث عالمي لليونسكو مع فنون صخرية ونقوش ممتدة عبر آلاف السنين من التاريخ البشري على طول طرق القوافل القديمة.",
    category: "ATTRACTION",
    lat: 18.1846,
    lng: 44.8728,
    avgDurationMins: 140,
    priceLevel: 1,
    rating: 4.6,
    reviewCount: 300,
    tags: ["history", "unesco", "culture", "photo-spot", "rock-art"],
    imageUrl: "https://images.unsplash.com/photo-1682687221038-404670f01c82?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1682687221038-404670f01c82?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1682687221038-404670f01c82?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=18.1846,44.8728",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "najran-museum",
    nameEn: "Najran Regional Museum",
    nameAr: "متحف نجران الإقليمي",
    descEn:
      "Modern museum with archaeological artifacts from the Ukhdood site, traditional costumes, tribal heritage displays, and a reconstruction of a Najrani house.",
    descAr:
      "متحف حديث يضم قطعًا أثرية من موقع الأخدود وأزياء تقليدية ومعروضات تراثية قبلية وإعادة بناء منزل نجراني.",
    category: "ATTRACTION",
    lat: 17.4935,
    lng: 44.1285,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.3,
    reviewCount: 310,
    tags: ["museum", "culture", "history", "heritage"],
    imageUrl: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=17.4935,44.1285",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "Al-aan-palace",
    nameEn: "Al Aan Palace",
    nameAr: "قصر العان",
    descEn:
      "Unique multi-story mud-brick tower house south of Najran, built with traditional techniques and decorated with intricate geometric patterns.",
    descAr:
      "برج سكني متعدد الطوابق من الطوب اللبن جنوب نجران، بُني بتقنيات تقليدية ومزخرف بأنماط هندسية معقدة.",
    category: "ATTRACTION",
    lat: 17.4218,
    lng: 44.1156,
    avgDurationMins: 60,
    priceLevel: 1,
    rating: 4.4,
    reviewCount: 250,
    tags: ["history", "architecture", "culture", "traditional"],
    imageUrl: "https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=17.4218,44.1156",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "najran-valley-wadi",
    nameEn: "Najran Valley (Wadi Najran)",
    nameAr: "وادي نجران",
    descEn:
      "Fertile valley stretching through the city with date palm gardens, seasonal floods, and traditional farming that has sustained civilization here for millennia.",
    descAr:
      "وادٍ خصب يمتد عبر المدينة مع بساتين النخيل وسيول موسمية وزراعة تقليدية أعالت الحضارة هنا لآلاف السنين.",
    category: "NATURE",
    lat: 17.5232,
    lng: 44.2018,
    avgDurationMins: 120,
    priceLevel: 1,
    rating: 4.3,
    reviewCount: 280,
    tags: ["nature", "agriculture", "photography", "valley"],
    imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=17.5232,44.2018",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "traditional-najrani-houses",
    nameEn: "Traditional Najrani Tower Houses",
    nameAr: "البيوت البرجية النجرانية التقليدية",
    descEn:
      "Distinctive multi-story mud-brick tower houses scattered around Najran, decorated with colorful geometric plaster art — a unique architectural tradition found nowhere else.",
    descAr:
      "بيوت برجية مميزة من الطوب اللبن متعددة الطوابق منتشرة حول نجران، مزينة بفن جص هندسي ملون — تقليد معماري فريد لا يوجد في أي مكان آخر.",
    category: "ATTRACTION",
    lat: 17.4876,
    lng: 44.1342,
    avgDurationMins: 60,
    priceLevel: 1,
    rating: 4.5,
    reviewCount: 190,
    tags: ["architecture", "culture", "heritage", "photography", "traditional"],
    imageUrl: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=17.4876,44.1342",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "najran-traditional-cuisine",
    nameEn: "Najran Traditional Cuisine Experience",
    nameAr: "تجربة المأكولات النجرانية التقليدية",
    descEn:
      "Savor authentic Najrani dishes like Masoob, Haneeth, and Mandi in traditional restaurants and local homes near the old city.",
    descAr:
      "تذوق أطباق نجرانية أصيلة مثل المعصوب والحنيذ والمندي في المطاعم التقليدية والمنازل المحلية بالقرب من المدينة القديمة.",
    category: "RESTAURANT",
    lat: 17.4945,
    lng: 44.1298,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.4,
    reviewCount: 350,
    tags: ["food", "culture", "local", "traditional"],
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=17.4945,44.1298",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "rub-al-khali-gateway",
    nameEn: "Rub' al Khali (Empty Quarter) Gateway",
    nameAr: "بوابة الربع الخالي",
    descEn:
      "Launch point into the world's largest sand desert. Guided desert safaris offer dune bashing, stargazing, and camping among towering red sand dunes.",
    descAr:
      "نقطة انطلاق إلى أكبر صحراء رملية في العالم. توفر رحلات السفاري الصحراوية المرشدة التطعيس ومراقبة النجوم والتخييم بين الكثبان الرملية الحمراء.",
    category: "ADVENTURE",
    lat: 17.3512,
    lng: 44.5218,
    avgDurationMins: 360,
    priceLevel: 3,
    rating: 4.8,
    reviewCount: 220,
    tags: ["desert", "adventure", "safari", "camping", "stargazing"],
    imageUrl: "https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=17.3512,44.5218",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "najran-dam-park",
    nameEn: "Najran Dam & Valley Park",
    nameAr: "سد نجران ومنتزه الوادي",
    descEn: "A large dam creating a scenic reservoir surrounded by gardens, walking paths, and picnic areas. Popular for birdwatching and sunset views over the water.",
    descAr: "سد كبير يشكل خزانًا خلابًا محاطًا بحدائق ومسارات مشي ومناطق نزهات. مشهور بمراقبة الطيور وإطلالات الغروب على الماء.",
    category: "NATURE",
    lat: 17.4800,
    lng: 44.2200,
    avgDurationMins: 120,
    priceLevel: 1,
    rating: 4.3,
    reviewCount: 680,
    tags: ["nature", "lake", "family", "sunset", "birds"],
    imageUrl: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=17.4800,44.2200",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "najran-traditional-souk",
    nameEn: "Najran Traditional Souk",
    nameAr: "سوق نجران التقليدي",
    descEn: "A vibrant market selling Najrani daggers (janbiyas), honey, incense, traditional clothing, and handicrafts. One of the most authentic souks in southern Saudi Arabia.",
    descAr: "سوق نابض بالحياة يبيع الجنابي النجرانية والعسل والبخور والملابس التقليدية والحرف اليدوية. أحد أكثر الأسواق أصالة في جنوب السعودية.",
    category: "SHOPPING",
    lat: 17.4920,
    lng: 44.1280,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 420,
    tags: ["shopping", "culture", "daggers", "handicrafts", "local"],
    imageUrl: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=17.4920,44.1280",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "najran-coffee-ceremony",
    nameEn: "Najrani Coffee Ceremony Experience",
    nameAr: "تجربة حفل القهوة النجرانية",
    descEn: "Join a traditional Najrani coffee ceremony featuring freshly roasted and ground Arabic coffee served with dates, dried fruit, and local sweets in a heritage setting.",
    descAr: "انضم لحفل قهوة نجراني تقليدي يقدم قهوة عربية محمصة ومطحونة طازجة مع التمور والفواكه المجففة والحلويات المحلية في أجواء تراثية.",
    category: "RESTAURANT",
    lat: 17.4950,
    lng: 44.1350,
    avgDurationMins: 60,
    priceLevel: 1,
    rating: 4.6,
    reviewCount: 290,
    tags: ["food", "coffee", "culture", "traditional", "experience"],
    imageUrl: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=17.4950,44.1350",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "najran-oasis-walk",
    nameEn: "Najran Oasis Walking Trail",
    nameAr: "ممشى واحة نجران",
    descEn: "Stroll through the lush Najran oasis with thousands of date palm trees, traditional mud houses, and irrigation channels (falaj) dating back centuries.",
    descAr: "تنزه عبر واحة نجران الغنّاء بآلاف أشجار النخيل والبيوت الطينية التقليدية وقنوات الري (الفلج) التي يعود تاريخها لقرون.",
    category: "NATURE",
    lat: 17.5000,
    lng: 44.1500,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.3,
    reviewCount: 350,
    tags: ["nature", "walking", "oasis", "palms", "heritage"],
    imageUrl: "https://images.unsplash.com/photo-1472396961693-142e6e269027?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1472396961693-142e6e269027?w=1920",
    imageUrls: ["https://images.unsplash.com/photo-1472396961693-142e6e269027?w=800"],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=17.5000,44.1500",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "najran-great-dam",
    nameEn: "Najran Great Dam",
    nameAr: "سد نجران الكبير",
    descEn:
      "Massive dam on Wadi Najran creating a scenic reservoir surrounded by mountains. Popular for fishing, picnics, and watching dramatic thunderstorm runoffs during the rainy season.",
    descAr:
      "سد ضخم على وادي نجران يشكل خزاناً خلاباً محاطاً بالجبال. مشهور بالصيد والنزه ومشاهدة السيول في موسم الأمطار.",
    category: "NATURE",
    lat: 17.5500,
    lng: 44.2500,
    avgDurationMins: 120,
    priceLevel: 1,
    rating: 4.3,
    reviewCount: 2800,
    tags: ["dam", "nature", "fishing", "mountains", "reservoir"],
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920",
    imageUrls: [
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    ],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=17.5500,44.2500",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "al-akhdar-village",
    nameEn: "Al Akhdar Heritage Village",
    nameAr: "قرية الأخضر التراثية",
    descEn:
      "Traditional Najrani village with distinctive multi-story mud-brick tower houses featuring colorful geometric window patterns. A living museum of Southern Arabian architecture.",
    descAr:
      "قرية نجرانية تقليدية بمنازل أبراج من الطوب اللبن متعددة الطوابق بأنماط نوافذ هندسية ملونة. متحف حي للعمارة العربية الجنوبية.",
    category: "CULTURAL",
    lat: 17.4900,
    lng: 44.1200,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.4,
    reviewCount: 1500,
    tags: ["village", "heritage", "architecture", "mud-brick", "culture"],
    imageUrl: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=1920",
    imageUrls: [
      "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=800",
    ],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=17.4900,44.1200",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "najran-archaeological-sites",
    nameEn: "Hamdan Archaeological Site",
    nameAr: "موقع حمدان الأثري",
    descEn:
      "Pre-Islamic archaeological site with ancient rock inscriptions, burial grounds, and stone circles dating back thousands of years. Features Himyarite-era artifacts.",
    descAr:
      "موقع أثري قبل الإسلام يضم نقوش صخرية قديمة ومدافن ودوائر حجرية تعود لآلاف السنين. يضم قطعاً أثرية من العصر الحميري.",
    category: "CULTURAL",
    lat: 17.6000,
    lng: 44.0800,
    avgDurationMins: 90,
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 900,
    tags: ["archaeology", "history", "inscriptions", "pre-islamic", "ancient"],
    imageUrl: "https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?w=1920",
    imageUrls: [
      "https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?w=800",
    ],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=17.6000,44.0800",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "najran-architecture-tour",
    nameEn: "Traditional Tower House Tour",
    nameAr: "جولة المنازل البرجية التقليدية",
    descEn:
      "Guided walking tour of Najran's distinctive tower houses showcasing the unique Najrani building style—multi-story mud-brick towers with white quartz decorative bands.",
    descAr:
      "جولة مشي موجهة في منازل نجران البرجية المميزة التي تعرض أسلوب البناء النجراني الفريد—أبراج طينية متعددة الطوابق بأشرطة زخرفية من الكوارتز الأبيض.",
    category: "CULTURAL",
    lat: 17.4950,
    lng: 44.1400,
    avgDurationMins: 120,
    priceLevel: 2,
    rating: 4.5,
    reviewCount: 1100,
    tags: ["architecture", "tour", "tower-house", "heritage", "walking"],
    imageUrl: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=1920",
    imageUrls: [
      "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=800",
    ],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=17.4950,44.1400",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
  {
    slug: "desert-rose-hunting",
    nameEn: "Desert Rose Crystal Hunting",
    nameAr: "البحث عن وردة الصحراء الكريستالية",
    descEn:
      "Hunt for naturally-formed gypsum crystal formations known as 'desert roses' in the sandy flats around Najran. A unique geological treasure hunt in the Arabian desert.",
    descAr:
      "البحث عن تشكيلات كريستال الجبس الطبيعية المعروفة باسم 'وردة الصحراء' في السهول الرملية حول نجران. صيد كنوز جيولوجي فريد.",
    category: "ADVENTURE",
    lat: 17.4000,
    lng: 44.3000,
    avgDurationMins: 180,
    priceLevel: 1,
    rating: 4.1,
    reviewCount: 700,
    tags: ["geology", "adventure", "desert", "crystals", "unique"],
    imageUrl: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800",
    heroImageUrl: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1920",
    imageUrls: [
      "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800",
    ],
    openingHours: null,
    googlePlaceId: null,
    officialUrl: null,
    tripAdvisorUrl: null,
    googleMapsUrl: "https://maps.google.com/?q=17.4000,44.3000",
    viatorUrl: null,
    getYourGuideUrl: null,
  },
];

