export const HERO_SLIDES = [
  {
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=1920",
    placeName: "Hegra (Madain Saleh)",
    placeNameAr: "الحِجر (مدائن صالح)",
    regionSlug: "madinah",
    attribution: "Unsplash",
    active: true,
  },
  {
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1586724237569-9c8004f02e04?w=1920",
    placeName: "Riyadh Skyline",
    placeNameAr: "أفق الرياض",
    regionSlug: "riyadh",
    attribution: "Unsplash",
    active: true,
  },
  {
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=1920",
    placeName: "Jeddah Al-Balad",
    placeNameAr: "جدة البلد",
    regionSlug: "makkah",
    attribution: "Unsplash",
    active: true,
  },
  {
    sortOrder: 4,
    imageUrl: "https://images.unsplash.com/photo-1632395370362-48fe5aa73e68?w=1920",
    placeName: "Elephant Rock, AlUla",
    placeNameAr: "صخرة الفيل، العلا",
    regionSlug: "madinah",
    attribution: "Unsplash",
    active: true,
  },
  {
    sortOrder: 5,
    imageUrl: "https://images.unsplash.com/photo-1586183189684-9e0c7e2b44e3?w=1920",
    placeName: "Ithra Cultural Center",
    placeNameAr: "مركز إثراء الثقافي",
    regionSlug: "eastern-province",
    attribution: "Unsplash",
    active: true,
  },
  {
    sortOrder: 6,
    imageUrl: "https://images.unsplash.com/photo-1609796484515-4c7c5e5e0e8e?w=1920",
    placeName: "Rijal Almaa Village",
    placeNameAr: "قرية رجال ألمع",
    regionSlug: "asir",
    attribution: "Unsplash",
    active: true,
  },
  {
    sortOrder: 7,
    imageUrl: "https://images.unsplash.com/photo-1682687982501-1e58ab814714?w=1920",
    placeName: "Wadi Disah",
    placeNameAr: "وادي ديسة",
    regionSlug: "tabuk",
    attribution: "Unsplash",
    active: true,
  },
  {
    sortOrder: 8,
    imageUrl: "https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=1920",
    placeName: "Diriyah Gate",
    placeNameAr: "بوابة الدرعية",
    regionSlug: "riyadh",
    attribution: "Unsplash",
    active: true,
  },
  {
    sortOrder: 9,
    imageUrl: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1920",
    placeName: "Farasan Islands",
    placeNameAr: "جزر فرسان",
    regionSlug: "jazan",
    attribution: "Unsplash",
    active: true,
  },
  {
    sortOrder: 10,
    imageUrl: "https://images.unsplash.com/photo-1542401886-65d6c61db217?w=1920",
    placeName: "Dhee Ayn Village",
    placeNameAr: "قرية ذي عين",
    regionSlug: "al-baha",
    attribution: "Unsplash",
    active: true,
  },
  {
    sortOrder: 11,
    imageUrl: "https://images.unsplash.com/photo-1547234935-80c7145ec969?w=1920",
    placeName: "Edge of the World",
    placeNameAr: "حافة العالم",
    regionSlug: "riyadh",
    attribution: "Unsplash",
    active: true,
  },
  {
    sortOrder: 12,
    imageUrl: "https://images.unsplash.com/photo-1537954916-0e4a8e4e1f2c?w=1920",
    placeName: "Taif Rose Gardens",
    placeNameAr: "حدائق ورد الطائف",
    regionSlug: "makkah",
    attribution: "Unsplash",
    active: true,
  },
  {
    sortOrder: 13,
    imageUrl: "https://images.unsplash.com/photo-1682687221038-404670f01c82?w=1920",
    placeName: "Jubbah Rock Art",
    placeNameAr: "نقوش جبة الصخرية",
    regionSlug: "hail",
    attribution: "Unsplash",
    active: true,
  },
  {
    sortOrder: 14,
    imageUrl: "https://images.unsplash.com/photo-1597690070758-f1dfb5506e07?w=1920",
    placeName: "Date Palm Oasis",
    placeNameAr: "واحة نخيل التمر",
    regionSlug: "al-qassim",
    attribution: "Unsplash",
    active: true,
  },
  {
    sortOrder: 15,
    imageUrl: "https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=1920",
    placeName: "Rajajil Standing Stones",
    placeNameAr: "أعمدة الرجاجيل",
    regionSlug: "al-jawf",
    attribution: "Unsplash",
    active: true,
  },
];
